### PR TITLE
For offline-capable views, require unique record name + enketo ID and prompt users to edit record name in case of collision

### LINKED ISSUE #416: Unsubmittable record in offline-capable view
**Describe the bug**
In some cases, Enketo fails to save a finalized record due a record name conflict with another record in the database. There isn't an obvious way to bypass this, so it could lead to loss of data (the bypass is to save a draft first and edit the suggested record name, and then re-load the record and submit it.

**To Reproduce**

0. Delete the indexedDb database by clicking on the secret button in the side slider (click on version first)
1. Launch two different forms (different Form ID in XForm) with the same form title
2. Open the offline-capable view of both forms on different tabs in the same browser
3. Save a draft record in one of the tabs using the autosuggested name (e.g. "Widgets - 1")
4. Submit a record in the other form (this will get the same name "Widgets - 1" but this will be invisible to the user

**Expected behavior**
For the last step to be completed without issues because the duplicate record name is for another form.

**Screenshots**

165811915-4253bdc0-fd79-4093-b5e6-b58b4b7864ad

**Additional context**

The issue is caused by the following two choices:
1. in the browser database both the instanceID and the record name need to be unique. The latter is so the list of records doesn't show records with the same name (so somewhat minor).
5. the auto-suggested (for draft) or auto-generated (for final never-saved) record name is usually the form title with an ordinal added to it (https://github.com/enketo/enketo-express/blob/master/public/js/src/module/controller-webform.js#L464). The ordinal is incremented per unique form.

If you have forms that have the same form title, a local record of one form may cause an issue in another form with the same title.

I'll take a shot at this and maybe clean up some of the mess (that I created)

### PR DESCRIPTION
**Pull request by MartijnR**
…than 1 form with the same title exist in the local database, closes #416

Closes #416 

#### I have verified this PR works with

-   [ ] Online form submission
-   [x] Offline form submission
-   [x] Saving offline drafts
-   [x] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [ ] None of the above

#### Why is this the best possible solution? Were any other approaches considered?

Options that were considered:

1 add another postfix (random string 2 or 3 characters) to record name
2 like previous but add the Enketo ID itself as the postfix or prefix (and hide it from the user in the form list?)
3 change database schema to no longer require record name to be unique (we haven't updated a database schema before, might be complicated)
4 like previous but roll our own uniqueness check that only looks at records under the same Enketo ID
5 change database schema to require uniqueness of record name + enketo ID
6 prompt users to edit the record name when this occurs
7 Since the record name is quite irrelevant for a finalized record (since it cannot be opened), we could do one of the above prefixes and postfixes only for finalized records.

I went for a combination of 5 and 6 since that covered the case of the bug report but also some other cases, where users provide their own record name for a draft record that conflicts with an existing record (even for the same form). That issue would remain even if we could completely eliminate the database index bug.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

The only issue is that users may end up with a remnant 'name' index in the records table of the browser database until they switch to another device, or browser, or clear storage. However, since the record name prompt feature is now there that will  only be a minor inconvenience.

### CODE REVIEW

File: public/js/src/module/controller-webform.js [hunk 1]
```diff
@@ -589,16 +598,21 @@ function _saveRecord(survey, draft, recordName, confirmed, errorMsg) {
...
                 error.target.error.name.toLowerCase() === 'constrainterror'
             ) {
-                errorMsg = t('confirm.save.existingerror');
-            } else if (!errorMsg) {
+                return _confirmRecordName(
+                    recordName,
+                    draft,
+                    t('confirm.save.existingerror')
+                ).then((name) => _saveRecord(survey, draft, name, true));
+            }
```
Comment (MartijnR) [inline public/js/src/module/controller-webform.js:614]: Part 1 of the fix is to give users the ability to resolve this (rare, except for developers) issue.

Theoretically even if we could fix the indexedDb uniqueness perfectly, it is still possible for users (and even Enketo's auto-generated record names) to create a duplicate record name (draft or final). So this resolves that.

File: public/js/src/module/store.js [hunk 2]
```diff
@@ -80,8 +80,16 @@ function init({ failSilently } = {}) {
...
+                            // https://github.com/enketo/enketo-express/issues/416
+                            // Version 3 of this database schema had a 'name' index that was set to be unique.
+                            // Although this index was removed in version 4, it will not be automatically deleted in
+                            // existing databases. This is a limitation of db.js. It should not cause significant issues
+                            // as the user will be prompted to edit the record name. Eventually, due to device upgrades,
+                            // or manual indexedDb deletion, this index will probably cease to exist in the world.
+                            //
+                            // to prevent showing the same record name in the queue
+                            recordName: {
+                                keyPath: ['name', 'enketoId'],
```
Comment (MartijnR) [inline public/js/src/module/store.js:92]: I tried many things to get the old 'name' index removed from an existing database, but I have concluded that it will require either an update to db.js (which will not happen) or a switch to a different indexedDb library.

Comment (eyelidlessness) [reply public/js/src/module/store.js:92]: Currently on mobile but thought I'd take a quick glance. I wonder if, instead of removing the `name` index it might be possible/sufficient to still include it but remove its uniqueness constraint?

Comment (MartijnR) [reply public/js/src/module/store.js:92]: Yes, good idea. Unfortunately, that has the same problem. It won't actually update for existing databases, so it seemed the equivalent to removing it (since we don't actually use the index to search for records anyway).

**Review by eyelidlessness — COMMENTED** [review]
It was really bugging me that there wasn't a clear way to remove the `name` index, so I went ahead and built a fix for that [here](https://github.com/eyelidlessness/enketo-express/commit/3a1379084c0262056a8f7cd151433559103eff59). Up to you @MartijnR whether you'd like to incorporate these changes or something like them.

**Comment by MartijnR** [comment]
thanks @eyelidlessness. I understand this was bugging you! :) Your solution to bypass db.js completely for the schema update looks great. I'll test it later too.

I'm trying to weigh the added code complexity against the benefits, and it's tricky. Atm I'd have a small preference to keep it simpler (since the confirm dialog takes care of working around the few cases that may arise). But I'll ponder a bit longer, and in any case, I have no strong feelings about it.

**Comment by MartijnR** [comment]
I tested it your db.js bypass for a clean schema update result and it works fine. 👍

**Comment by eyelidlessness** [comment]
@MartijnR Thank you for validating the proposed change. I'd prefer to bring it in if that's okay with you. I spent a decent amount of time reworking and validating the solution, and have high confidence that it's safe.

**Comment by MartijnR** [comment]
Let's do it! Thank you!

**Comment by eyelidlessness** [comment]
Great! Also for posterity, it occurred to me another good reason to bring it in is that the schema definition would otherwise be different from the actual schema, which could be hard to track down in the future.

**Review by eyelidlessness — APPROVED** [review]
