### PR TITLE
Remove online form cache

### LINKED ISSUE #218: Media files with spaces in their filename do not load
With a XLSForm like this one

name | type | label | media::image
-- | -- | -- | --
hey | note | some image | image with spaces in the name.jpg
nspacio | note | nospace | nospace.jpg

`nospace.jpg` loads but `image with spaces in the name.jpg` does **not**

### LINKED ISSUE #286: Form's default media references are removed after submission
**Describe the bug**

Found while reproducing #218. When a form has default `jr:` media URLs, those references are no longer resolved after submitting a record.

**To Reproduce**

1. Create a form with default `jr:` media references
2. Submit a new record
3. Reload the form

**Expected behavior**

The default media references will be reloaded.

**Browser and OS (please complete the following information):**

 - OS: macOS
 - Browser: Chrome

**Additional context**

This bug was very likely introduced in #269. I'm already working on a fix.

### PR DESCRIPTION
**Pull request by eyelidlessness**
This change addresses problems introduced in #269:

- The previous last-saved implementation introduced caching of forms in online mode, because the last-saved instance was stored along with the Survey. That behavior has been removed, instead storing last-saved records in a new `lastSavedRecords` store.
- Fixes #286, #287 regressions, ensuring binary defaults and media labels are once again resolved correctly (except for media labels with spaces in the `jr:` URL, which will be addressed separately to resolve #218)

### CODE REVIEW

File: public/js/src/module/controller-webform.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ import records from './records-queue';
 import $ from 'jquery';
 import encryptor from './encryptor';
 import formCache from './form-cache';
+import { getLastSavedRecord, populateLastSavedInstances } from './last-saved';
```
Comment (eyelidlessness) [inline public/js/src/module/controller-webform.js:17]: I tried to keep changes here as minimal as possible, as this module is still untested. The changes here are to support:

- The signature change to `uploadRecord`
- Continuing to ensure last-saved instances are populated when the form is reset after submitting/queueing/saving a draft record

File: public/js/src/module/form-cache.js [hunk 2]
```diff
@@ -7,7 +7,10 @@ import events from './event';
 import settings from './settings';
 import connection from './connection';
 import assign from 'lodash/assign';
-import encryptor from './encryptor';
```
Comment (eyelidlessness) [inline public/js/src/module/form-cache.js:10]: As with many of the changes in `connection.js`, the changes here remove last-saved implementation details, which are now implemented in `last-saved.js`.

File: public/js/src/module/last-saved.js [hunk 3]
```diff
@@ -0,0 +1,152 @@
+import encryptor from './encryptor';
```
Comment (eyelidlessness) [inline public/js/src/module/last-saved.js:1]: All of the last-saved implementation now lives here. These changes should _mostly_ look familiar, as it's very similar to the previous implementation. The primary differences are:

- Last-saved records are no longer stored in `surveys`, they're written to a new `lastSavedRecords` store
- Some code style changes:
    - Named exports declared at the definition site; this improves the ability to follow references through the project, as well as makes it clearer at definition site whether a function is intended to be used outside the module
    - Arrow functions (they're just more idiomatic)
- Not technically a change, but calling out that _if_ a survey is already cached for offline mode, online mode will still update that cache's last-saved `externalData` instances when a survey changes. This ensures caches do not store stale last-saved data, particularly in cases where a last-saved instance may have been removed from the form.

File: public/js/src/module/records-queue.js [hunk 4]
```diff
@@ -12,6 +12,7 @@ import exporter from './exporter';
 import { t } from './translator';
 import $ from 'jquery';
 import formCache from './form-cache';
+import { setLastSavedRecord } from './last-saved';
```
Comment (eyelidlessness) [inline public/js/src/module/records-queue.js:15]: The changes here account for the API changes in `connection.js`.

File: public/js/src/module/store.js [hunk 5]
```diff
@@ -945,5 +963,6 @@ export default {
     dynamicData: dataStore,
     record: recordStore,
     flush,
-    dump
+    dump,
+    get lastSavedRecords() { return server.lastSavedRecords; },
```
Comment (eyelidlessness) [inline public/js/src/module/store.js:967]: I tried to keep the changes to `store.js` to a minimum, keeping as much last-saved logic in `last-saved.js` as possible. These minor changes were necessary because the store's schema all has to be defined at initialization time. This breaks a bit with the pattern for other stores, as `last-saved.js` references the `db.js` interfaces directly rather than a wrapper around them.

File: test/client/config/karma.conf.js [hunk 6]
```diff
@@ -37,6 +40,15 @@ module.exports = config => {
...
             },
+            plugins: [
+                alias(
+                    Object.fromEntries(
+                        Object.entries( pkg.browser ).map( ( [ key, value ] ) => (
+                            [ key, path.resolve( cwd, `${value}.js` ) ]
+                        ) )
+                    )
+                ),
+            ],
```
Comment (eyelidlessness) [inline test/client/config/karma.conf.js:51]: This change, as well as the one in `build.js`, addresses another media regression (and potentially several other regressions 😬), this time caused by #289:

1. [`enketo-core`](https://github.com/enketo/enketo-core/blob/53eaeb5e6533e302087e700b203725efbfeb1aad/package.json#L90-L97) defines and implements a set of aliased modules whose functionality it depends on
2. [`enketo-express`](https://github.com/enketo/enketo-express/blob/ca75e8eeb9481eddb695538949beaf419843a083/package.json#L123-L129) also defines those aliases, but overrides those implementations.
3. When we switched to esbuild, it failed to account for those overrides, causing the `enketo-express` build to use `enketo-core`'s behavior for those modules.

Comment (eyelidlessness) [reply test/client/config/karma.conf.js:51]: We should consider consolidating relevant portions of these configs, so the two builds don't diverge in the future.

File: test/client/form-cache.spec.js [hunk 7]
```diff
@@ -195,113 +195,4 @@ describe( 'Client Form Cache', () => {
...
-                    return getFormPartsSpy.getCall( 0 ).returnValue;
-                } )
-                .then( formParts => {
-                    expect( getSpy.called ).to.equal( false );
-                    expect( setSpy.called ).to.equal( false );
-                    expect( initResult ).to.deep.equal( formParts );
-                } )
-                .then( done, done );
-        } );
-    } );
```
Comment (eyelidlessness) [inline test/client/form-cache.spec.js:306]: These tests are no longer relevant, because _none_ of the modes access the form cache anymore.

**Comment by MartijnR** [comment]
Hi @eyelidlessness,

I had a quick glance and especially at the PR comments you made. Looks good. There is just a merge conflict atm. 

I'd like to do some real-life testing in the next few days.

**Comment by eyelidlessness** [comment]
@MartijnR sorry it took a bit to resolve conflicts. Rebase got pretty confusing 😬 but should be good to go now!

**Review by MartijnR — APPROVED** [review]
Thanks. Code looks good to me and I did some real-life testing with regular form and forms that use the last-saved feature. Online-only views no longer cache the form itself. Database structure update seems to work as desired.

**Comment by MartijnR** [comment]
Since some other related issues need fixing before releasing a new version, I will just go ahead and merge.

**Comment by MartijnR** [comment]
In a short while if there are no objections raised....

**Comment by lognaturel** [comment]
We’ve got some quality assurance planned in the next few days but if you’re satisfied with your checks a release would be most appreciated!

**Comment by MartijnR** [comment]
Oh, that would be great. Now I am tempted to just wait... :)

**Comment by lognaturel** [comment]
That sounds fine to me! @eyelidlessness would waiting a few days make more conflicts accumulate? @getodk/testers are back from vacation on Tues of next week.

**Comment by eyelidlessness** [comment]
I hope not but I don't mind dealing with them if they do, if holding off is preferred!
