### PR TITLE
Fix: validate CSV header names according to XML spec

### LINKED ISSUE #529: Allow dashes in CSV column names
[This forum post](https://forum.getodk.org/t/odk-collect-v2023-1-beta-select-traces-and-shapes-from-map-google-drive-deprecation-banner/40412/8?u=ln) points out that dashes aren't allowed in CSV column names.

Indeed: https://github.com/enketo/enketo-express/blob/bd09481bd35dc61c65bfdfb1cf91a7ca5b2829d0/public/js/src/module/utils.js#L266

We should allow them, that's a common pattern, and dashes are allowed in XML element names.

### PR DESCRIPTION
**Pull request by eyelidlessness**
Closes #529.

#### I have verified this PR works with

-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [x] None of the above

I think the tests are sufficient validation, but I'm happy to run it if preferred.

#### What else has been done to verify that this works as intended?

Several tests. Not exhaustive, but go a bit beyond the issue as the change is broader.

#### Why is this the best possible solution? Were any other approaches considered?

The XML specification explicitly defines a grammar for names.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

It's possible the character ranges defined in the spec are more permissive than we want, but if that's the case it would also be true for our use of native APIs like `DOMParser`.

### CODE REVIEW

File: public/js/src/module/utils.js [hunk 1]
```diff
@@ -260,16 +260,74 @@ function _serializeQueryComponent(name, value) {
...
+
+    const nameStartChar = `[${nameStartCharRanges.join('')}]`;
+    const nameChar = `[${nameCharRanges.join('')}]`;
+    const name = `^${nameStartChar}${nameChar}*$`;
+
+    return new RegExp(name, 'u');
+})();
+
+/**
+ * TODO (2023-02-27): Is the below restriction really necessary? It seems we could:
```
Comment (lognaturel) [inline public/js/src/module/utils.js:307]: I think mostly it's just not that useful. We wouldn't be using standard XML concepts because the namespace declaration would be elsewhere. So we might as well leave "namespacing" to user conventions (e.g. foo.the_thing vs bar.the_thing).
