### PR TITLE
Fix: single-column CSV

### LINKED ISSUE #488: Single-column CSV fails to parse
[ODK Forum](https://forum.getodk.org/t/psa-workaround-for-odk-central-online-form-filling-unable-to-auto-detect-delimiting-character-error/39562)

We should be able to detect the single-column case and proceed instead of passing on the error: https://github.com/mholt/PapaParse/issues/165#issuecomment-75575797

### PR DESCRIPTION
**Pull request by eyelidlessness**
Closes #488.

#### I have verified this PR works with

-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [X] None of the above

#### What else has been done to verify that this works as intended?

I'll manually validate if requested, but I think the tests should be sufficient.

#### Why is this the best possible solution? Were any other approaches considered?

I thought about looking into using another CSV parser, but that has its own set of regression risks.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

It's possible there is some valid or invalid case I haven't considered/tested.

#### Do we need any specific form for testing your changes? If so, please attach one.

N/A

### CODE REVIEW

File: public/js/src/module/utils.js [hunk 1]
```diff
@@ -108,13 +108,40 @@ function getTitleFromFormStr(formStr) {
...
+    const input = csv.trim();
     const options = {
         skipEmptyLines: true,
     };
-    const result = Papa.parse(csv.trim(), options);
+
+    let result = Papa.parse(input, options);
+    const { errors } = result;
+
+    if (errors[0]?.code === 'UndetectableDelimiter' && errors[1] == null) {
```
Comment (lognaturel) [inline public/js/src/module/utils.js:123]: `errors[1] == null` feels like it relies on JS quirks whereas a check that `errors` has a length of 1 would better match the intent.

**Review by lognaturel — APPROVED** [review]
Small stylistic thing I'd change that's not a big deal.

**Review by lognaturel — APPROVED** [review]
