### PR TITLE
Fix/missing media healing offline 419

### LINKED ISSUE #419: A failing form media (e.g. video) download in offline-capable form is never retried
**Describe the bug**
This is mostly relevant to forms that include a large media file (e.g. video). If during the attempted caching of such a resource the download fails or the user refreshes the browser tab, the resource is not stored in indexedDb.

**To Reproduce**

use live  https://enke.to/x/caAGzYyU or local:

```bash
curl --user enketorules: -d "server_url=https://enketo-aggregate.appspot.com&form_id=video-label_" http://localhost:8005/api/v2/survey/offline
```

1. load form on a mobile device *
2. refresh during loading of the video
3. at some point after refreshing (perhaps multiple times), you end up with this broken video state.

*  So far nobody has been able to reproduce this on a desktop even when throttling the connection to slow 3G. I personally have only been able to reproduce it on an iPad (only tried Safari), but others could (easily) reproduce on Android&Chrome. I suspect having an excellent mobile data connection makes it more difficult to reproduce. 

**Expected behavior**
For Enketo to have a mechanism to re-attempt downloading of uncached resources.

**Screenshots**

Screen Shot 2022-05-06 at 3 02 34 PM

**Additional context**
It's clear from the code that this condition was not foreseen.

**During development and testing it is probably very useful to load the form and simply remove the video from indexedDb in Chrome (right-click on entry in "resources" table)**

### PR DESCRIPTION
**Pull request by MartijnR**
Closes #419

#### I have verified this PR works with

-   [x] Offline form-with-media loading, in particular these cases:

1. a media file fails to load the first time the form is cached
2. newly added repeats will show cached media files correctly

#### What else has been done to verify that this works as intended?

Some tests were added.

#### Why is this the best possible solution? Were any other approaches considered?

It seems the most efficient way for an offline-capable view to recover from failed-to-download (due to large size, poor Internet) media files.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Users will be happier. This is intentional. Regressions risks maybe for some unidentified edge cases with form media.

#### Do we need any specific form for testing your changes? If so, please attach one.

Any form will media will do. I put a curl snippet in the issue.

### CODE REVIEW

File: public/js/src/module/form-cache.js [hunk 1]
```diff
@@ -359,43 +347,62 @@ function _reflect(task) {
...
-            // create a resourceURL
-            resourceUrl = URL.createObjectURL(resource.item);
-            // add this resourceURL as the src for all elements in the group
-            elements.forEach((element) => {
-                element.src = resourceUrl;
+        const request = store.survey.resource
+            .get(survey.enketoId, src)
+            .then(async (resource) => {
+                if (!resource || !resource.item) {
+                    // no need to try/catch here as we don't care about catching failures
```
Comment (MartijnR) [inline public/js/src/module/form-cache.js:374]: bad or okay?

File: test/client/form-cache.spec.js [hunk 2]
```diff
@@ -275,5 +275,87 @@ describe('Client Form Cache', () => {
...
+            let resultSurvey;
+
+            /** @type {SinonSpy} */
+            let storeSurveyUpdateSpy;
+
+            beforeEach((done) => {
+                getFileSpy.restore();
+                getFileSpy = sandbox
+                    .stub(connection, 'getMediaFile')
+                    .callsFake(() => Promise.reject(new Error('Fail!')));
```
Comment (MartijnR) [inline test/client/form-cache.spec.js:289]: `.stub().throws()` doesn't work with the original pre-PR code. The reason it would work here is probably because I used await without try and catch (and throwing). I like to be able to run the tests on the old code, so used callsFake instead.

**Review by eyelidlessness — APPROVED** [review]
Thanks @MartijnR!

I've read this through a few times, to make sure I understand the diff, a lot of which is only moving existing behavior around to accommodate refetching missing media. After a few passes, I feel pretty confident that this change is safe.

I definitely wouldn't want to block this fix, but it did get me thinking that we may want to revisit how offline media/resource caching is handled. I'll file a separate issue, but the gist is that we could handle requests for resources at their online URL, with a [`FetchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent) handler in the service worker.
