### PR TITLE
Don't disable the upload button so much

### LINKED ISSUE #43: When going from offline to online, upload button does not get re-enabled
_From @MartijnR on April 27, 2016 19:41_

to reproduce:

1. Go offline
2. Add final record to queue
3. Upload button gets disabled at next upload attempt
4. Go online
5. Upload button remains disabled until next automatic attempt

So small issue. Can't do manual uploads for a short period (unless refreshing page).

_Copied from original issue: kobotoolbox/enketo-express#489_

### PR DESCRIPTION
**Pull request by MartijnR**
… online with a queue ready to send, closes #43

Also fixes a bug where the upload button gets re-enabled after a user saves another record record whilst offline.

Closes #410

#### I have verified this PR works with

-   [ ] Online form submission
-   [x] Offline form submission
-   [x] Saving offline drafts
-   [ ] Submitting offline drafts - ?? (this is not a supported feature)
-   [ ] Editing submissions
-   [ ] Form preview
-   [ ] None of the above

### CODE REVIEW

**Comment by lognaturel** [comment]
> Submitting offline drafts - ?? (this is not a supported feature)

I believe this is saving a draft, closing the browser window. Then coming back later and submitting. So not like telepathically sending while offline 😅. I think we've been using `online` and `offline` to refer to the "Enketo mode" rather than to the actual connectivity status. (@eyelidlessness please correct me if I got any of that wrong)

Let's indeed get this in before the 6 year anniversary on the 27th!!

File: public/js/src/module/records-queue.js [hunk 1]
```diff
@@ -124,6 +122,27 @@ function getAutoSavedRecord() {
     return get(getAutoSavedKey());
 }
 
+/**
+ * Updates the disabled/enabled state of the upload button.
+ */
+function _updateUploadButtonState() {
```
Comment (MartijnR) [inline public/js/src/module/records-queue.js:128]: Enabling and disabling the upload button was messy, as it was directly done in two different functions. And it appeared this resulted in a yet-undiscovered bug as well (when offline and adding an additional "final" record to the queue when the button was disabled, the upload button was enabled again until the next call to uploadQueue). 

To address issue #401, we'd be possibly adding a third place, increasing the chance of bugs even further.

I therefore chose to use a new function that always sets the button correctly no matter how many times and where it is called. It now is just a matter of calling it at the right times (at least).

It still relies on the semi-global `finalRecordPresent` and `uploadOngoing` variables. I considered getting rid of those, but failed to find a better solution and decided to consider it out of scope.

File: public/js/src/module/records-queue.js [hunk 2]
```diff
@@ -189,10 +208,12 @@ function _setUploadIntervals() {
     setTimeout(() => {
         uploadQueue();
     }, 30 * 1000);
-    // interval to check upload queued records
+    // interval to upload queued records
     setInterval(() => {
         uploadQueue();
     }, 5 * 60 * 1000);
+    // interval to disable/enable upload button
+    setInterval(_updateUploadButtonState, 0.5 * 60 * 1000);
```
Comment (MartijnR) [inline public/js/src/module/records-queue.js:216]: The 30 second interval was chosen as a compromise between reducing the number server requests and anxious users waiting for the button to become enabled so they can click it.

P.S. navigator.online does not work for this purpose. I think the best way to reliably check the online status is what we're currently doing with a HTTP request.

**Comment by MartijnR** [comment]
>I believe this is saving a draft, closing the browser window. 

Yes, that's what I suspected afterwards.

I checked that too!

**Comment by eyelidlessness** [comment]
> I think we've been using `online` and `offline` to refer to the "Enketo mode" rather than to the actual connectivity status. (@eyelidlessness please correct me if I got any of that wrong)

Generally, but as a shorthand. The modes are "online only" versus "offline capable". In this case it is checking whether a request to `/connection` succeeds and returns a non-cached response. This certainly would determine online connectivity, but @MartijnR may be able to clear up if it's also used to determine server availability?

If it's only to determine connectivity, we could solve this (for supporting browsers) without a network request or a timer:

```js
let isOnline = navigator.onLine;

const setOnlineState = () => {
  isOnline = navigator.onLine;
  
  console.log('isOnline', isOnline);
};

window.addEventListener('online', setOnlineState);
window.addEventListener('offline', setOnlineState);
```

Tested this in a Codepen, and it's instantaneous (as I'd expect). We'll still need a fallback for Safari, support for these events was only added in 15.4. Not great to have redundant implementations, but we'll likely be able to use just the events in a not-distant future.

**Comment by MartijnR** [comment]
I'll check why `navigator.online` didn't work and if that's still the case. (Enketo used to use it). Thanks!

**Comment by lognaturel** [comment]
My 2 cents:
- This makes improvements and looks low risk to me so it makes sense to include in the release we're about to do (unless there's a risk I've missed)
- At a higher level, I don't understand the benefit of disabling the upload button. It seems like enabling it, letting the user click it, and then letting them know that they're offline would give the user more awareness of what's going on while completely eliminating the issue for users who know they're online and want to send immediately. If the goal is to help the user understand what state they're in, changing the `Submit` button to something like `Queue for submission` seems like it would be more helpful. So perhaps another thing to consider would be to remove the disabling behavior altogether.

**Comment by MartijnR** [comment]
> I don't understand the benefit of disabling the upload button

Thanks for taking a step back and blowing my mind! Haha. 👍 It does indeed seem much better to:

1. have a busy state (consistent with the one Enketo is already using for other buttons) when uploads are ongoing
2. only disable the upload button when there are no finalized records in the queue
3. use an alert (dialog) when the user clicks the enabled upload button, but Enketo determines it is offline

I shall look into this and implement if I don't discover some issue with that approach.

**Comment by lognaturel** [comment]
Hurray, I love it. The race against the six-year anniversary resumes. 😂😂

File: app/views/surveys/component/_side-slider.pug [hunk 3]
```diff
@@ -2,10 +2,9 @@ aside.record-list.side-slider
 	button.btn-icon-only.close(type="button", aria-hidden="true") ×
 	h3(data-i18n='record-list.title')= t('record-list.title')
 	p(data-i18n='record-list.msg1')= t('record-list.msg1')
-	progress.record-list__upload-progress
```
Comment (MartijnR) [inline app/views/surveys/component/_side-slider.pug:5]: It turns out we already had a separate progress bar on top of the 'side slider' that shows the records. I think it didn't have much utility because of the feedback already provided when succeeding or failing to upload records (animation when removing a record, and showing error messages below failing record). I think this gives sufficient feedback on the progress.

**Review by eyelidlessness — APPROVED** [review]
Thanks @MartijnR! I tried this out in a variety of scenarios and it works as expected. I was hopeful that we could eliminate the need for the network request, and while it's certainly possible I think this is fine for now.

To follow up on the earlier discussion of `navigator.isOnline` and the `online`/`offline` events for posterity: I was able to verify that they do work across the major browsers. However they all have some varying degree of delay. That's likely _okay_ for most real world usage, but it would also explain why it may have appeared to produce false positives.

**Comment by MartijnR** [comment]
> @MartijnR do you know of user network configs where that would happen?

Yes, back in the days in humanitarian aid, we had a LAN network (for printing, filesharing) but without Internet or only occasional Internet. Data collectors may come home from the field after data collecting and automatically connect to the LAN. 

Not a huge deal perhaps, but Enketo would try to submit the queue every 5 minutes in that case.

**Comment by MartijnR** [comment]
> I was hopeful that we could eliminate the need for the network request,
We could also consider changing the order, so that `getOnlineStatus` would only be called when there are finalized records in the queue (so we reverse the two checks). In that case the remaining extra network request is more justified because it will be far more likely that it will prevent lots of other heavier network requests (submissions).

**Comment by eyelidlessness** [comment]
The other, possibly more common scenarios are WAN connection loss/ISP outage.

**Comment by lognaturel** [comment]
> would only be called when there are finalized records in the queue (so we reverse the two checks)

That would sound good to me! But probably not a huge deal.

> The other, possibly more common scenarios are WAN connection loss/ISP outage.

Yes, yes, sorry, I convinced myself that you'd be kicked off the LAN if that happened so I was looking for scenarios more like what @MartijnR described. I agree WAN outages are common so the events are probably not a good fit.
