### PR TITLE
Fix: works around issue with canvas not printing in puppeteer's PDF g…

### LINKED ISSUE #512: PDFs show empty canvas for loaded drawings, signatures and annotated images
**Describe the bug**
When using the /view/pdf endpoint and loading a record that contains e.g. a signature, that signature is not shown on the pdf. An empty canvas is shown instead.

**To Reproduce**
```
curl --user enketorules: -d "server_url=https://api.ona.io/enketo&form_id=widgets&instance=<widgets><text_widgets><text>mart</text></text_widgets><media_widgets><signature>test.jpg</signature></media_widgets></widgets>&instance_id=someUUID&instance_attachments[test.jpg]=https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg" http://localhost:8005/api/v2/instance/view/pdf > ~/Downloads/pdf-signature-bug.pdf
```

**Expected behavior**
For the signature to be shown just like the /view endpoints shows it. For the example above this can be seen by going to the URL returned by:

```bash
curl --user enketorules: -d "server_url=https://api.ona.io/enketo&form_id=widgets&instance=<widgets><text_widgets><text>mart</text></text_widgets><media_widgets><signature>test.jpg</signature></media_widgets></widgets>&instance_id=someUUID&instance_attachments[test.jpg]=https://upload.wikimedia.org/wikipedia/commons/a/a9/Example.jpg" http://localhost:8005/api/v2/instance/view
```

**Screenshots**

Screenshot 2023-01-11 at 2 34 53 PM

**Browser and OS (please complete the following information):**

- Since this issue is puppeteer related the (headless) browser is part of enketo-express (5.0.2).

**Additional context**
It looks like this inactive old issue describes it: https://bugs.chromium.org/p/chromium/issues/detail?id=809065.

This likely means we need to work around it.

### PR DESCRIPTION
**Pull request by MartijnR**
…eneration, closes #512

#### I have verified this PR works with

-   [ ] Online form submission
-   [ ] Offline form submission
-   [ ] Saving offline drafts
-   [ ] Loading offline drafts
-   [ ] Editing submissions
-   [ ] Form preview
-   [x] None of the above

#### What else has been done to verify that this works as intended?

The code is only used for PDF generation. Therefore, I've only tested the PDF API endpoints. 

#### Why is this the best possible solution? Were any other approaches considered?

I concluded that the issue is a bug in puppeteer in the printToPDF implementation of a '2d' canvas. Therefore, it seemed best to work around it. In the PDF view, there is no need for a real canvas, so converting canvases to images seemed an acceptable solution.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Regression risks are styling changes in the drawing widget or general images that unintentionally affect drawings in the PDF view.

#### Do we need any specific form for testing your changes? 

See the linked issue for API calls to reproduce the issue and test the fix.

### CODE REVIEW

File: app/lib/pdf.js [hunk 1]
```diff
@@ -64,6 +64,34 @@ async function get(url, options = {}) {
...
             });
 
+        /*
+         * This works around an issue with puppeteer not printing canvas
+         * images that were loaded from a file.
+         * It is likely this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=809065
+         * (though not WebGL-related as some of the commenters suggest)
+         */
+        await page.evaluate(() => {
+            /* eslint-env browser */
```
Comment (MartijnR) [inline app/lib/pdf.js:74]: It's unclear what the scope of this eslint-env override is. Setting it to `eslint-env: node` after this page.evaluate function doesn't actually seem to switch it back.

**Review by eyelidlessness — APPROVED** [review]

**Comment by MartijnR** [comment]
thanks!
