### PR TITLE
Fixed: Form preview fails with IDBObjectStore error

### LINKED ISSUE #279: Form preview fails with IDBObjectStore error
**Describe the bug**
Form preview on https://getodk.org/xlsform when running master (b252f0eaca67dee94bc18737e82cd02c13ac0d0e) errors out when previewing a simple one question form.
```
Failed to execute 'get' on 'IDBObjectStore': No key or key range specified.
```

**Browser and OS (please complete the following information):**
 - OS: macOS
 - Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Additional context**
Issue was introduced in https://github.com/enketo/enketo-express/pull/269 (9b8891a9aacd9605222cec3aad9a7ece0ce43aa9). PRs before that one work as I expect.

### PR DESCRIPTION
**Pull request by eyelidlessness**
Fixes #279.

This introduces two changes to fix a regression introduced in #269:

- The store is bypassed in initialization when a form is previewed. As noted in a code comment, this was implemented in form-cache.js primarily to enable testing, but likely more appropriate in enketo-webform.js
- `getFormParts` now only calls `getLastSavedRecord` when `settings.type` is `other`, which is the default value when filling a form (versus `preview`, `single`, `edit`, `view`)

### CODE REVIEW

File: public/js/src/module/form-cache.js [hunk 1]
```diff
@@ -30,6 +30,14 @@ let hash;
  * @return {Promise<Survey>}
  */
 function init( survey ) {
+    /**
+     * Note: it would probably be better if this were in enketo-webform.js, as it
+     * doesn't relate to the form cache per se. It's included here for testability.
+     */
+    if ( settings.type === 'preview' ) {
```
Comment (lognaturel) [inline public/js/src/module/form-cache.js:37]: This doesn't need to be `settings.type !== 'other'`?

Comment (eyelidlessness) [reply public/js/src/module/form-cache.js:37]: Bringing additional detail from Slack to consolidate discussion...

> I have one question inline. It’s not totally clear to me whether there’s any difference between preview and single, edit, view and only preview is tested.

My understanding from the [docs](https://apidocs.enketo.org/v2#/get-survey-all) was that `single` is a "single-submit" survey, which I just validated. However I now see that `single` is also "online-only", so I think you're right! In which case, I think the modification in connection.js is probably unnecessary, and both `formCache.init` and `getLastSavedRecord` could both perform this check to bypass except in `other` mode.

**Review by lognaturel — APPROVED** [review]

**Comment by lognaturel** [comment]
There's a failing test that I'm pretty sure is flaky and will eventually pass on re-run. Either @MartijnR can rerun or @eyelidlessness you should be able to use the force push a spacing change to the commit message trick.

**Review by MartijnR — APPROVED** [review]
Thanks for the quick fix!
