### PR TITLE
fixed: The app UI strings in newly created repeats are not translated…

### LINKED ISSUE #526: newly created repeats are not translated
**Describe the bug**
Only the first repeat gets the correct translation of error messages (and probably other UI language strings). Other repeats get error messages in English.

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Load [this form](https://docs.google.com/spreadsheets/d/1rXVpByyMMkPaTcikymf4YIpHxCNJu4XGTsSW8BZwx2Q/edit?usp=sharing) in French (e.g. by adding ?lang=fr to the URL, or setting browser language to French) as a regular online-only webform with a URL format like http://localhost:8005/AzhkK25g?lang=fr
2. Add text longer than 1 character in the first repeat
3. Create another repeat
4. Add text longer than 1 character to the new repeat
5. Note that the second constraint error message is displayed in English instead of French.

**Expected behavior**
Both constraint error messages to display in French

**Screenshots**
Screenshot 2023-02-16 at 1 02 50 PM

**Additional context**
Enketo Express 6.0.0 (didn't check older versions)

Here is another interesting use case, a form without languages defined has the same problem: 
[repeaterrors.xml.txt](https://github.com/enketo/enketo-express/files/10759082/repeaterrors.xml.txt) (I've added this new scenario to [this sheet](https://docs.google.com/spreadsheets/d/1CigMLAQewcXi-OJJHi_JQQ-fJXOam99livM0oYrtbkk/edit#gid=1504432290) as case X). Since Enketo has no knowledge of the language used in the form it should display the browser language for UI components. The solution for this issue is likely the same for both, but would be good to check.

It is quite remarkable that this bug appears to have been around since the creation of Enketo and was never reported until now.

### PR DESCRIPTION
**Pull request by MartijnR**
… to the current language, closes #526

Closes #526

#### I have verified this PR works with

* translated forms
* non-translated forms

#### What else has been done to verify that this works as intended?

Nothing. I'm sorry to have not tried to add a test. 

#### Why is this the best possible solution? Were any other approaches considered?

Enketo deals with XForms strings in Enketo Core and UI strings in Enketo Express. Only an "add-repeat" event handler was considered as a solution. It was placed underneath a similar handler that handles user language switching.

However, I realized afterwards that an alternative solution would be to localize the repeat templates (`form.repeats.templates`) both upon load and when the user switches a language. That way new repeats are always in the current language at the time of creation without manipulation.

I don't have a preference for one of these at the moment. I'd be happy to change this PR to use the latter solution if preferred.

#### How does this change affect users? 

It will make them happier when using forms that have repeats, especially users that do not speak English.

#### Do we need any specific form for testing your changes? If so, please attach one.

Please see 2 forms added to the issue #526.

### CODE REVIEW

**Comment by MartijnR** [comment]
Am working on a PR for the alternative solution as it might be better.

File: public/js/src/module/controller-webform.js [hunk 1]
```diff
@@ -873,6 +873,12 @@ function _setEventHandlers(survey) {
             );
         });
     }
+    // This actually belongs in gui.js but that module doesn't have access to the form object.
```
Comment (eyelidlessness) [inline public/js/src/module/controller-webform.js:876]: I've noticed a fair number of cases like this—where certain behavior is either implemented in an unexpected place, or where there's a layer of indirection so it can be in an expected place—specifically because of access to the form object, or lack thereof.

In enketo/enketo-transformer#171 I introduced a (currently dev-only) global `enketo` object. In that PR it's only used by tests and benchmarks run in a browser context, but I think it's worth considering whether a single Enketo-scoped global might be of some benefit across Transformer/Core/Express. There are some things which are **inherently** already global singletons, and I don't think there'd be any shame in making that explicit.

I could see that opening up a lot of opportunities to clean up some very low-hanging tech debt fruit, while also making some existing implicit data dependencies at least a bit more clear.

All of that said, this is of course fine for now.

**Review by eyelidlessness — APPROVED** [review]
