### PR TITLE
Identify form type prefix when Enketo at subpath

### LINKED ISSUE #195: Form type is not identified for Enketo installs at subpath
**Describe the bug**
If Enketo is not at the root, form type (preview, single, etc), is not correctly identified.

**To Reproduce**
* Install Enketo at a subpath (e.g. by installing ODK Central)
* Go to a `/single` URL
* Fill out the form and submit
* On submission, notice that there's no redirect and that more submissions can be made.

**Expected behavior**
Form type should be identified regardless of where Enketo is installed.

**Additional context**
As @matthew-white notes, https://github.com/enketo/enketo-express/blob/4995059ecc21d76a50c30ba6286a598413df6a5e/public/js/src/module/settings.js#L65-L76 is the culprit.

We propose using `includes` to match the offline detection (e.g. `window.location.pathname.includes( '/preview/' )`). That feels safe to me because it seems vanishingly unlikely someone would use one of the form types as part of the subpath for their Enketo installation.

### PR DESCRIPTION
**Pull request by lognaturel**
Closes #195 

This is a less risky approach than #196 which entirely removes this code block.

I manually tried `preview` and `single` prefixes.

### CODE REVIEW

File: public/js/src/module/settings.js [hunk 1]
```diff
@@ -63,13 +63,13 @@ settings.languageOverrideParameter = queryParams.lang ? {
 settings.maxSize = DEFAULT_MAX_SIZE;
 
 // add type
-if ( window.location.pathname.indexOf( '/preview' ) === 0 ) {
+if ( window.location.pathname.includes( '/preview/' ) ) {
```
Comment (MartijnR) [inline public/js/src/module/settings.js:66]: This wouldn't identify https://enketo.getodk.org/preview?form=https://xlsform.getodk.org/downloads/h6cp6h3m/mini_form.xml (as redirected to in  https://getodk.org/xlsform/) as a preview. That may not actually matter in reality, but let's add `|| window.location.pathname.endsWith('/preview')` just to make sure we don't run into issues (in the future).

**Comment by lognaturel** [comment]
Thanks, @MartijnR!

Sorry about #196, I got carried away. I'm still getting used to the tooling and I think I forgot to run `grunt` so convinced myself `settings` was the same thing in the two places. 😬 Glad I gave you more to pick from in the buffet!

I see the small CI failure is also on `master` so I'll rebase when there's an update there.
